swagger: '2.0'
info:
  title: Bank Argent Transactions API
  description: Contains API endpoints for transaction management
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      tags:
        - Transaction Module
      summary: Get all transactions
      description: Returns all transactions for the current month, grouped by account.
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/TransactionList'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error

  /transactions/{transactionId}:
    get:
      tags:
        - Transaction Module
      summary: Get transaction details
      description: Returns details of a specific transaction.
      parameters:
        - in: path
          name: transactionId
          type: string
          required: true
          description: ID of the transaction to retrieve details for.
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

    put:
      tags:
        - Transaction Module
      summary: Update transaction details
      description: Updates details of a specific transaction.
      parameters:
        - in: path
          name: transactionId
          type: string
          required: true
          description: ID of the transaction to update.
        - in: body
          name: body
          description: Updated transaction details (only note and category can be modified)
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

    delete:
      tags:
        - Transaction Module
      summary: Delete note and category of a transaction
      description: Deletes the note and category of a specific transaction.
      parameters:
        - in: path
          name: transactionId
          type: string
          required: true
          description: ID of the transaction to update.
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details updated successfully
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

definitions:
  TransactionList:
    type: object
    properties:
      transactions:
        type: array
        items:
          $ref: '#/definitions/Transaction'
  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
        description: Date of the transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        description: Amount of the transaction
      type:
        type: string
        description: Type of the transaction
      category:
        type: string
        description: Category of the transaction
        enum:
          - food
          - other
      note:
        type: string
        description: Additional note for the transaction
  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
        description: Updated category of the transaction
      note:
        type: string
        description: Updated note for the transaction
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
